Also add error message to the workflow log (#394)

diff --git a/.github/workflows/comment-on-asciidoc-changes.yml b/.github/workflows/comment-on-asciidoc-changes.yml
--- a/.github/workflows/comment-on-asciidoc-changes.yml
+++ b/.github/workflows/comment-on-asciidoc-changes.yml
@@ -41,4 +41,6 @@ jobs:
 
       - name: Error if .asciidoc files changed
         if: steps.check-files.outputs.any_changed == 'true'
-        run: exit 1
+        run: |
+          echo '::error::It looks like this PR modifies one or more .asciidoc files. These files are being migrated to Markdown, and any changes merged now will be lost. See the https://elastic.github.io/docs-builder/migration/freeze/index.html for details.'
+          exit 1
